<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>NetCom Learning : Break Countdown Timer</title>
<meta name="keywords" content ="class break countdown timer">
<meta name="description" content="Countdown timer for showing time left for break during training session">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" type="text/css" href="http://a.netcomlearning.com/css/styles_new3.css">
</head>
<body bgcolor="#cacaca">

<center>
<div style='border:10px solid white;width:650px;padding:0 0 0 0px;margin:100 0 0 0px;'>
<div style='border:1px solid #666666;width:650px;padding:30 0 0 0px;margin:0 0 0 0px;background-color:white;'>

<table width='100%' border='0' cellpadding='5' cellspacing='5' bgcolor='#ffffff'>
<tr>
<td align='center'>
        <img src='http://a.netcomlearning.com/i/logo3.png' alt='NetCom Learning'>
</td>
</tr>

<tr>
<td align='center'>
<?php
        include($_SERVER[DOCUMENT_ROOT] . '/inc/be_right_back_countdown_timer.inc');
?>
</td>
</tr>
</table>
	
</div>
</div>
</center>

</body>
</html>
